PYTHON=python3

testTennis:
	$(PYTHON) main.py tennis-attr.txt tennis-train.txt tennis-test.txt

testBool:
	$(PYTHON) main.py bool-attr.txt bool-train.txt bool-test.txt

testIris:
	$(PYTHON) main.py iris-attr.txt iris-train.txt iris-test.txt


testIrisNoisy:
	$(PYTHON) corrupt-main.py iris-attr.txt iris-train.txt iris-test.txt